# 2024 Munro Research, All rights reserved
name: Build and Deploy

#trigger on push to main
on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: europe-west2 # registry region
  GKE_CLUSTER: munro-research-cluster-0 # cluster nam
  GKE_ZONE: europe-west2-a # cluster zone
  DEPLOYMENT_NAME: website # deployment name
  REPOSITORY: docker #registry repo
  IMAGE: website # image name
  NAMESPACE: munro # deployment namespace

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Authentication via credentials json
    - name: Google authentication via credentials json
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
        username:  _json_key
        password: ${{ secrets.GCP_CREDENTIALS }}
        
    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest"
        
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl rollout restart deployment/$DEPLOYMENT_NAME --namespace $NAMESPACE
